### ISSUE TITLE
CSE7759

### ISSUE THREAD

**Issue by r-jordan** [xoseperez/hlw8012#10]
There are now another version of Son off Pow with the chip CSE7759. They are very similar. May be we can use your library changing the constants?
Can you take a look on the schematics?
Thanks!

**Comment by xoseperez** [comment]
Yes, actually ESPurna uses this HLW8012 library for the CSE7766 and CSE7759. Check my comment there and the previous commit: https://github.com/xoseperez/espurna/issues/737#issuecomment-398878301
