### ISSUE TITLE
Add CSE7759 and CSE7766

### ISSUE THREAD

**Issue by birdoplo** [xoseperez/hlw8012#12]
Add CSE7759 and CSE7766 for library Arduino Core ESP8266.

**Comment by xoseperez** [comment]
The CSE* use different protocol and it's a completely different library. If you want to, you can use the https://github.com/ingeniuske/CSE7766 library by @ingeniuske, based on my code in ESpurna.

**Comment by tcpipchip** [comment]
Hi, i am using that ingeniuske routine and i am only getting the Voltage, other values are ZERO. Can you help us ?
Then i started a program from scratch and again, only getting Voltage.
