### ISSUE TITLE
Cloning issue in Platformio

### ISSUE THREAD

**Issue by Kalekulan** [xoseperez/hlw8012#8]
I'm trying to build espurna project in platformio, but I get a fatal error when trying to clone hlw8012.

´´Cloning into 'C:\Temp\espurna-1.12.5\code\.piolibdeps\_tmp_installing-kzaloo-package'...
warning: Could not find remote branch 1.1.0 to clone.
fatal: Remote branch 1.1.0 not found in upstream origin´´

I'm not sure if this is an hlw8012 issue, but I would appreciate your comment on it.

Thanks!

**Comment by xoseperez** [comment]
This repo was moved to github recently. Probably your copy of ESPurna is not up to date and still points to the old repo. You can either update your ESPurna working repo or change the reference to this library in the platformio.ini file.

**Comment by Kalekulan** [comment]
I see that it's been fixed in 1.12.6. Thanks!
